version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - atomicnet
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: logsmith/php
    volumes:
     - .:/var/www/html
    networks:
     - atomicnet
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "secret"
    volumes:
      # - mysqldata:/var/lib/mysql
      - ./data/development.sql:/docker-entrypoint-initdb.d/development.sql
    networks:
      - atomicnet
    # command: ["sh", "-c", "envsubst '$$ENV' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
networks:
  atomicnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
